# Generated by Django 2.2.1 on 2019-05-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='array_width',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
