# Generated by Django 2.2.1 on 2019-05-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0002_item_array_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='array_width',
        ),
        migrations.AddField(
            model_name='item',
            name='image_width',
            field=models.IntegerField(null=True),
        ),
    ]
